export const VALIDATION_ERRORCODE_NOT_EMPTY = 1;
export const VALIDATION_ERRORCODE_INVALID_FORMAT = 2;
export const VALIDATION_ERRORCODE_TOO_LONG = 8;
export const VALIDATION_ERRORCODE_TOO_SHORT = 4;
